import Home from "./page"
import AboutMe from "@/components/About"
import Connect from "@/components/Connect"
import Footer from "@/components/Footer"
import Header from "@/components/Header"
import Navigation from "@/components/Navigation"
import ProjectSection from "@/components/ProjectSection"
import { render, screen, fireEvent, waitFor } from "@testing-library/react"
import { AboutMockData, ConnectMockData, mockProjects } from "@/utils/mockData"
